### PR TITLE
`length` as assertion => `lengthOf`

### PR DESCRIPTION
**Pull request by shvaikalesh**
Related to https://github.com/chaijs/chai/issues/684

### CODE REVIEW

**Comment by keithamus** [comment]
👍 LGTM

**Comment by lucasfcosta** [comment]
LGTM too!
Since @meeber still had to think about on Chai's main repo I'll leave this open for him to merge if he feels confortable with it.

**Comment by shvaikalesh** [comment]
So with https://github.com/chaijs/chai/pull/897 we favor `lengthOf` over `length` for cross-env consistency. I believe this change is still relevant.

**Comment by keithamus** [comment]
Agreed. Let's get CI agreeing before we merge though 😉

**Comment by shvaikalesh** [comment]
Seems like auth issues:
```
remote: Anonymous access to chaijs/chai-docs.git denied.
fatal: Authentication failed for 'https://@github.com/chaijs/chai-docs/'
```

**Comment by keithamus** [comment]
in which case merged 😄

**Pull request merged**
