### PR TITLE
Chai 2.0.0 release

### PR DESCRIPTION
**Pull request by keithamus**
Generated site for 2.0.0

### CODE REVIEW

**Comment by keithamus** [comment]
@logicalparadox I believe this one will be for you again.

**Comment by logicalparadox** [comment]
Also need to change version tag [here](https://github.com/chaijs/chai-docs/blob/master/data/codex.json#L12).

**Comment by keithamus** [comment]
@logicalparadox added. Anything else missing or good to go?

**Comment by logicalparadox** [comment]
Did you rebuild after changing `codex.json`? The version tag is used in the jade templates for display on the home page and force the browser to use a non-cached version of chai/chai tests for the browser test suite.

**Comment by keithamus** [comment]
:blush: yeah... I should have twigged that. Ok, this should be it.

**Pull request merged**
