### PR TITLE
Update chai to 2.1.0.

### PR DESCRIPTION
**Pull request by jmm**
Resolves online test suite failures in the process.

### CODE REVIEW

**Comment by keithamus** [comment]
Awesome work @jmm, thanks kindly!

**Comment by keithamus** [comment]
@logicalparadox I'm not sure if any work needs to be done here to get this onto http://chaijs.com?

**Comment by logicalparadox** [comment]
Yes, I still have to manually publish, old school.

`2.1.0` is live on chaijs.com

**Comment by jmm** [comment]
Thanks @keithamus and @logicalparadox.

**Pull request merged**
