### PR TITLE
Fixed double scrollbar issue and added back missing @params

### PR DESCRIPTION
**Pull request by aaronsofaly**
Fixed issues #126 and #128.

### CODE REVIEW

**Comment by keithamus** [comment]
This looks pretty great @aaronsofaly. Any chance you could push up your fork to your personal `gh-pages` branch - so we can have a look at it working?

**Comment by aaronsofaly** [comment]
Hey @keithamus, I pushed up my gh-pages branch. You can see it here, http://aaronsofaly.github.io/chai-docs/.

For the @params I basically converted the jade template from the old_site repo to work with the new liquid template. Here's the lines I converted, https://github.com/chaijs/chai-docs/blob/old_site/template/api.jade#L31-L48.

For issue #126, this is the screenshot for how the @params used to look, https://cloud.githubusercontent.com/assets/113730/14697670/01cd23ac-0754-11e6-9947-33dea52140aa.png. And this is how it looks now, http://aaronsofaly.github.io/chai-docs/api/bdd/#method_include.

On a side note, my github project page is returning a 404 for http://aaronsofaly.github.io/chai.js. This is because the URL should be re-written to http://aaronsofaly.github.io/chai-docs/chai.js. The reference for the chai.js file is found in _site/index.html. `<script src="/chai.js" type="text/javascript"></script>` So I don't know if there's something we can do to make that work correctly.

**Comment by aaronsofaly** [comment]
It looks like the @params tag.types were italicized on the old site so we should probably update the styling on the new site to match.

**Comment by aaronsofaly** [comment]
Okay, I updated the @params to have spans and css classes so that they have the proper styling.

**Comment by keithamus** [comment]
Good work @aaronsofaly 😄

**Comment by keithamus** [comment]
Aaand its live 💯 🎉 http://chaijs.com/api/bdd/#method_a

**Pull request merged**
