### PR TITLE
Fix minor typo in the docstring of property

### PR DESCRIPTION
**Pull request by astorije**

### CODE REVIEW

**Comment by aaronsofaly** [comment]
Hey @astorije. The docs are compiled from chai's repo. So to fix a typo you actually need to submit a PR to chai's repo. [This looks like the line](https://github.com/chaijs/chai/blob/master/lib/chai/core/assertions.js#L859).

**Comment by astorije** [comment]
Doh! The worst part is, I knew it! Thanks for the catch @aaronsofaly 
Opened https://github.com/chaijs/chai/pull/714.

**Comment by astorije** [comment]
Is this one still worth merging or closing altogether?

**Comment by aaronsofaly** [comment]
Haha, no worries!

I'd close this PR since merging it would cause the docs site to be out of sync with chai's repo which is the source of truth.

**Comment by astorije** [comment]
Alright, closing then. @keithamus, feel free to reopen (or tell me to reopen) if necessary.

**Pull request closed without merging**
